=== izharikov/web-programming/7th_lab/xml/lab.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fpmi.bsu.by"
           xmlns="http://fpmi.bsu.by"
           elementFormDefault="qualified">

    <xs:element name="compositions">
        <xs:complexType>
            <xs:sequence minOccurs="0" maxOccurs="unbounded">
                <xs:element name="composition">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="year" type="xs:integer"/>
                            <xs:element name="days-in-top" type="xs:integer"/>
                            <xs:element name="duration" type="duration"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="duration">
        <xs:attribute name="hours" type="xs:integer" default="0" use="optional"/>
        <xs:attribute name="min" type="xs:integer" default="0" use="optional"/>
        <xs:attribute name="sec" type="xs:integer" default="0" use="optional"/>
    </xs:complexType>
</xs:schema>

=== izharikov/web-programming/7th_lab/xml/compositions.xml
<?xml version="1.0"?>
<compositions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://fpmi.bsu.by" xsi:schemaLocation="http://fpmi.bsu.by lab.xsd">
    <composition>
        <type>Rock</type>
        <name>Wait And Bleed</name>
        <year>2000</year>
        <days-in-top>300</days-in-top>
        <duration min="4" sec="2"/>
    </composition>

    <composition>
        <type>Classic</type>
        <name>Mozart 5th Symphony</name>
        <year>1450</year>
        <days-in-top>1000</days-in-top>
        <duration min="5" sec="2"/>
    </composition>

    <composition>
        <type>Rap</type>
        <name>Eminem : I'm not afraid</name>
        <year>2004</year>
        <days-in-top>200</days-in-top>
        <duration min="3" sec="43"/>
    </composition>

</compositions>
